      - key: RATELIMIT_ENABLED
        value: "true"          # change from "false"
      - key: SQLALCHEMY_POOL_SIZE
        value: "3"
      - key: SQLALCHEMY_MAX_OVERFLOW
        value: "2"
      - key: SQLALCHEMY_POOL_TIMEOUT
        value: "10"
      - key: SQLALCHEMY_POOL_RECYCLE
        value: "280"
      - key: SENTRY_DSN
        sync: false