"""phase 3: locations and suggestions

Revision ID: 22db60538e17
Revises: 3a1b21b629cd
Create Date: 2026-10-05 15:34:01.809544

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision = '22db60538e17'
down_revision = '3a1b21b629cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('locations',
    sa.Column('campus_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('category', sa.String(length=32), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('point', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('polygon', geoalchemy2.types.Geometry(geometry_type='POLYGON', srid=4326, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('opening_hours', sa.String(length=120), nullable=True),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('verified_by', sa.String(length=36), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['campus_id'], ['campuses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['verified_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('locations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_locations_campus_id'), ['campus_id'], unique=False)
        batch_op.create_index('ix_locations_campus_status', ['campus_id', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_locations_category'), ['category'], unique=False)
        batch_op.create_index('ix_locations_point_gist', ['point'], unique=False, postgresql_using='gist')
        batch_op.create_index(batch_op.f('ix_locations_status'), ['status'], unique=False)

    op.create_table('location_suggestions',
    sa.Column('campus_id', sa.String(length=36), nullable=False),
    sa.Column('proposed_by', sa.String(length=36), nullable=True),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('category', sa.String(length=32), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lng', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('moderated_by', sa.String(length=36), nullable=True),
    sa.Column('moderated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('moderation_note', sa.String(length=255), nullable=True),
    sa.Column('approved_location_id', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['approved_location_id'], ['locations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['campus_id'], ['campuses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['moderated_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['proposed_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('location_suggestions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_location_suggestions_campus_id'), ['campus_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_location_suggestions_proposed_by'), ['proposed_by'], unique=False)
        batch_op.create_index(batch_op.f('ix_location_suggestions_status'), ['status'], unique=False)

    with op.batch_alter_table('campus_reports', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'locations', ['location_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('campus_reports', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('location_suggestions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_location_suggestions_status'))
        batch_op.drop_index(batch_op.f('ix_location_suggestions_proposed_by'))
        batch_op.drop_index(batch_op.f('ix_location_suggestions_campus_id'))

    op.drop_table('location_suggestions')
    with op.batch_alter_table('locations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_locations_status'))
        batch_op.drop_index('ix_locations_point_gist', postgresql_using='gist')
        batch_op.drop_index(batch_op.f('ix_locations_category'))
        batch_op.drop_index('ix_locations_campus_status')
        batch_op.drop_index(batch_op.f('ix_locations_campus_id'))

    op.drop_table('locations')
    # ### end Alembic commands ###
