"""phase 2: campus pulse

Revision ID: 3a1b21b629cd
Revises: 98a56c86c48c
Create Date: 2026-10-05 13:04:20.355270

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a1b21b629cd'
down_revision = '98a56c86c48c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('campus_reports',
    sa.Column('campus_id', sa.String(length=36), nullable=False),
    sa.Column('location_id', sa.String(length=36), nullable=True),
    sa.Column('category', sa.String(length=48), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('image_key', sa.String(length=255), nullable=True),
    sa.Column('reported_by', sa.String(length=36), nullable=True),
    sa.Column('reported_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('confidence', sa.String(length=16), nullable=False),
    sa.Column('confirmation_count', sa.Integer(), nullable=False),
    sa.Column('disagreement_count', sa.Integer(), nullable=False),
    sa.Column('flag_count', sa.Integer(), nullable=False),
    sa.Column('moderation_status', sa.String(length=16), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['campus_id'], ['campuses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reported_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('campus_reports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_campus_reports_campus_id'), ['campus_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_campus_reports_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_campus_reports_expires_at'), ['expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_campus_reports_location_id'), ['location_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_campus_reports_reported_by'), ['reported_by'], unique=False)
        batch_op.create_index(batch_op.f('ix_campus_reports_status'), ['status'], unique=False)
        batch_op.create_index('ix_reports_campus_status_expires', ['campus_id', 'status', 'expires_at'], unique=False)

    op.create_table('report_confirmations',
    sa.Column('report_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['report_id'], ['campus_reports.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('report_id', 'user_id', name='uq_confirmation_per_user_per_report')
    )
    with op.batch_alter_table('report_confirmations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_report_confirmations_report_id'), ['report_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_report_confirmations_user_id'), ['user_id'], unique=False)

    op.create_table('report_flags',
    sa.Column('report_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('reason', sa.String(length=120), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['report_id'], ['campus_reports.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('report_id', 'user_id', name='uq_flag_per_user_per_report')
    )
    with op.batch_alter_table('report_flags', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_report_flags_report_id'), ['report_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_report_flags_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('report_flags', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_report_flags_user_id'))
        batch_op.drop_index(batch_op.f('ix_report_flags_report_id'))

    op.drop_table('report_flags')
    with op.batch_alter_table('report_confirmations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_report_confirmations_user_id'))
        batch_op.drop_index(batch_op.f('ix_report_confirmations_report_id'))

    op.drop_table('report_confirmations')
    with op.batch_alter_table('campus_reports', schema=None) as batch_op:
        batch_op.drop_index('ix_reports_campus_status_expires')
        batch_op.drop_index(batch_op.f('ix_campus_reports_status'))
        batch_op.drop_index(batch_op.f('ix_campus_reports_reported_by'))
        batch_op.drop_index(batch_op.f('ix_campus_reports_location_id'))
        batch_op.drop_index(batch_op.f('ix_campus_reports_expires_at'))
        batch_op.drop_index(batch_op.f('ix_campus_reports_category'))
        batch_op.drop_index(batch_op.f('ix_campus_reports_campus_id'))

    op.drop_table('campus_reports')
    # ### end Alembic commands ###
